@url = http://localhost:4000/api
@posts = {{url}}/posts

###
GET {{posts}}

###
GET {{posts}}/11

###
DELETE {{posts}}/12

###
POST {{posts}}
Content-Type: application/json

{
  "title": "post-eh",
  "contents": "Do u even express?"
}